credentials:
  usernames:
    admin:
      email: teacher@school.edu
      name: "Admin"
      password: "$2b$12$erDymWBmdZyn98F7MGgqcOQzdfnmOCB09tJ8jMHmLHpaBlvVb1cE2"

cookie:
  expiry_days: 30
  key: "some_secret_random_key_12345"
  name: "auth_cookie"
